project:
  type: website
  output-dir: docs
  preview: 
    port: 4321
  resources:
    - "*.mp3"
    - /h5p
    - /sci-writing/material-FT081
  
 
website:
  title: "Prof. Vitor R. Coluci"
  site-url: https://www.explora.ft.unicamp.br
  navbar:
    left:     
      - href: research/research.qmd
        text: Pesquisa 
      - href: teaching/teaching.qmd
        text: Ensino
      - href: outreach/outreach.qmd
        text: Extensão
      - href: publications/publications.qmd
        text: Publicações
      - href: facilities/facilities.qmd
        text: Infra-estrutura
      - href: people/people.qmd
        text: Equipe
  page-footer:
    "Prof. Vitor R. Coluci 2025 - FT/UNICAMP/Limeira"


format:
  html:
    lang: pt
    page-layout: full
    theme:
      light: [flatly, light_mode.scss]
      dark: [darkly, dark_mode.scss]
    css: styles.css
    toc: true



