---
title: "Músicas"
format:
  html:
    toc: false
---

## [Anna Julia](./musicas/Anna-Julia.qmd)

## [Anunciação](./musicas/Anunciacao.qmd)

## [Asa Branca](./musicas/Asa-Branca.qmd)

## [Debaixo dos caracóis dos seus cabelos](./musicas/Debaixo-dos-caracois-dos-seus-cabelos.qmd)

## [É o amor](./musicas/E-o-amor.qmd)

## [É preciso saber viver](./musicas/E-preciso-saber-viver.qmd)

## [Esperando na Janela](./musicas/Esperando-na-Janela.qmd)

## [Essa tal liberdade](./musicas/Essa-tal-liberdade.qmd)

## [Evidências](./musicas/Evidencias.qmd)

## [Lua Branca](./musicas/Lua-Branca.qmd)

## [Não deixe o samba morrer](./musicas/Nao-deixe-o-samba-morrer.qmd)

## [O sol](./musicas/O-sol.qmd)

## [O Xote das meninas](./musicas/o-xote-das-meninas.qmd)

## [Pense em mim](./musicas/Pense-em-mim.qmd)

## [Poema](./musicas/Poema.qmd)

## [Sangue latino](./musicas/Sangue-latino.qmd)

## [Seu amor ainda é tudo](./musicas/Seu-amor-ainda-eh-tudo.qmd)

## [Tocando em frente](./musicas/Tocando-em-frente.qmd)

## [Tristeza](./musicas/Tristeza.qmd)

## [Tristeza do Jeca](./musicas/Tristeza-do-Jeca.qmd)

## [Você não me ensinou a te esquecer](./musicas/Voce-nao-me-ensinou-a-te-esquecer.qmd)