---
title: Publicações
---

**2024**

**2023**

51- [Animações para o ensino de Matemática usando o Manim-Python](ttps://doi.org/10.21711/2319023x2023/pmo1104), Professor de Matemática Online, 2023

50- [ORUN-VR2: a VR serious game on the projectile kinematics: design, evaluation, and learning outcomes](http://dx.doi.org/10.1007/s10055-023-00824-w), . Virtual Reality, 2023

**2022**

49- [Animações de conceitos da teoria de erros usando Manim/Python](http://dx.doi.org/10.1590/1806-9126-rbef-2021-0239), Revista Brasileira de Ensino de Física, 2022

48- [Accelerated causal Green's function molecular dynamics](http://dx.doi.org/10.1016/j.cpc.2022.108378), Computer Physcis Communication, 2022

47- [Modeling and characterization of MoNbTiW refractory multi-principal element alloy](http://dx.doi.org/10.1016/j.jallcom.2022.167062), J. of Alloys and Compounds, 2022

**2021**

46- [Mechanical properties of single-walled penta-graphene-based nanotubes: A DFT and Classical molecular dynamics study](http://dx.doi.org/10.1016/j.chemphys.2021.111187), Chemical Physics, 2021

45- [Integration of digital games and remote laboratories with real-time visualization: Conception, Implementation and Evaluation.](http://dx.doi.org/10.1590/1806-9126-rbef-2021-0202), Revista Brasileira de Ensino de Física, 2021 

44- [Educational Digital Games integrated into Remote Labs: systematic and mapping reviews](http://dx.doi.org/10.5753/rbie.2021.29.0.547), Revista Brasileira de Informática na Educação, 2021

**2020**

43- [Light interference pattern measurements from automated low-cost Young’s double-slit experiments.](http://dx.doi.org/10.1590//1806-9126-rbef-2020-0006), Revista Brasileira de Ensino de Física, 2020

**2019**

42- [Interaction of graphene oxide with cell culture medium: Evaluating the fetal bovine serum protein corona formation towards in vitro nanotoxicity assessment and nanobiointeractions](https://doi.org/10.1016/j.msec.2019.02.066), Materials Science and Engineering: C, 2019

41- [Initial stages of graphene oxide cracking in basic media](https://doi.org/10.1016/j.carbon.2018.10.037), Carbon, 2019

**2018**

40- [Generalized Green’s function molecular dynamics for canonical ensemble simulations](https://link.aps.org/doi/10.1103/PhysRevE.97.053310), Physical Review E, 2018

39- [Compressive response and deformation mechanisms of vertically aligned helical carbon nanotube forests](https://aip.scitation.org/doi/abs/10.1063/1.5008983), Applied Physics Letters, 2018

**2017** 

38- [The motion of a ball moving down a circular path](http://dx.doi.org/10.1119/1.4972177), American Journal of Physics, 2017

**2016**

37- [Torsional “superplasticity” of graphyne nanotubes](https://doi.org/10.1016/j.carbon.2015.09.039), Carbon, 2016

**2015**

**2014**

36- [Noncovalent Interaction with Graphene Oxide: The Crucial Role of Oxidative Debris](https://doi.org/10.1021/jp409501g), Journal of Physical Chemistry C, 2014

**2013**

35- [Illustration of uncertanties in measurements by using free fall experiments](http://www.scielo.br/pdf/rbef/v35n2/26.pdf), Revista Brasileira De Ensino De Fisica, 2013

**2012**

34- [Comparative parametric method 6 (PM6) and Recife model 1 (RM1) study of trans-stilbene](https://doi.org/10.1080/08927022.2011.597392), Molecular Simulation, 2012

**2011**

33- [Mechanisms of the rotational dynamics of C-70 in C-70-cubane heteromolecular crystals](https://doi.org/10.1063/1.3671948), Journal of Chemical Physics, 2011

32- [Ordered phases of encapsulated diamondoids into carbon nanotubes](https://doi.org/10.1088/0957-4484/22/31/315708), Nanotechnology, 2011

31- [Understanding the interaction of multi-walled carbon nanotubes with mutagenic: organic pollutants using computational modeling and biological experiments](https://doi.org/10.1016/j.trac.2010.11.013), Trac-Trends in Analytical Chemistry, 2011

**2010**

30- [Molecular Dynamics Simulations of Stretching, Twisting and Fracture of Super Carbon Nanotubes with Different Chiralities: Towards Smart Porous and Flexible Scaffolds](https://doi.org/10.1166/jctn.2010.1483), Journal of Computational and Theoretical Nanoscience, 2010

29- [Topologically Closed Macromolecules Made of Single Walled Carbon Nanotubes-‘Super’-Fullerenes](https://doi.org/10.1166/jnn.2010.2467), Journal of Nanoscience and Nanotechnology, 2010

**2009**

28- [Thermophoretically driven carbon nanotube oscillators](https://doi.org/10.1063/1.3276546), Applied Physics Letters, 2009

**2008**

27- [Carbon nanotubes as reinforcement elements of composite nanotools](https://doi.org/10.1021/nl0729633), Nano Letters, 2008

26- [Designing conducting polymers using bioinspired ant algorithms](https://doi.org/10.1016/j.cplett.2008.01.037), Chemical Physics Letters, 2008

25- [Entanglement and the nonlinear elastic behavior of forests of coiled carbon nanotubes](https://doi.org/10.1103/PhysRevLett.100.086807), Physical Review Letters, 2008

24- [Modeling the auxetic transition for carbon nanotube sheets](https://doi.org/10.1103/PhysRevB.78.115408), Physical Review B, 2008

23- [Rotational dynamics and polymerization of C(60) in C(60)-cubane crystals: A molecular dynamics study](https://doi.org/10.1063/1.2965885), Journal of Chemical Physics, 2008

22- [Sign change of Poisson’s ratio for carbon nanotube sheets](https://doi.org/10.1126/science.1149815), Science, 2008

**2007**

21- [Atomistic simulations of the mechanical properties of ‘super’ carbon nanotubes](https://doi.org/10.1088/0957-4484/18/33/335702), Nanotechnology, 2007

20- [Hydrogen storage in carbon nanoscrolls: An atomistic molecular dynamics study](https://doi.org/10.1016/j.cplett.2007.04.060), Chemical Physics Letters, 2007

**2006**

19- [Prediction of giant electroactuation for papyruslike carbon nanoscroll structures: First-principles calculations](https://doi.org/10.1103/PhysRevB.74.085414), Physical Review B, 2006

18- [Synthetic melanin films: Assembling mechanisms, scaling behavior, and structural properties](https://doi.org/10.1063/1.2200401), Journal of Applied Physics, 2006

17- [Geometric and electronic structure of carbon nanotube networks: ‘super’-carbon nanotubes](https://doi.org/10.1088/0957-4484/17/3/001), Nanotechnology, 2006 (Highlighted by Nature [here](https://www.nature.com/articles/439512a))

**2005**

16- [Carcinogenic classification of polycyclic aromatic hydrocarbons through theoretical descriptors](https://doi.org/10.1002/qua.20529), International Journal of Quantum Chemistry, 2005

15- [Chaotic signature in the motion of coupled carbon nanotube oscillators](https://doi.org/10.1088/0957-4484/16/4/041), Nanotechnology, 2005

14- [Prediction of ordered phases of encapsulated C-60, C-70, and C-78 inside carbon nanotubes](https://doi.org/10.1021/nl047930r), Nano Letters, 2005

**2004**

13- [Comparative parametric method 5 (PM5) study of trans-stilbene](https://doi.org/10.1016/j.theochem.2004.08.017), Journal of Molecular Structure-Theochem, 2004

12- [Gigahertz nanomechanical oscillators based on carbon nanotubes](https://doi.org/10.1088/0957-4484/15/4/012), Nanotechnology, 2004

11- [New families of carbon nanotubes based on graphyne motifs](https://doi.org/10.1088/0957-4484/15/4/006), Nanotechnology, 2004

10- [Structure and dynamics of carbon nanoscrolls](https://doi.org/10.1021/nl0497272), Nano Letters, 2004

9- [Theoretical investigation of electromechanical effects for graphyne carbon nanotubes](https://doi.org/10.1063/1.1772756), Journal of Chemical Physics, 2004

**2003**

8- [Families of carbon nanotubes: Graphyne-based nanotubes](https://doi.org/10.1103/PhysRevB.68.035430), Physical Review B, 2003

7- [How similar are branching networks in nature? A view from the ocean: Caribbean gorgonian corals](https://doi.org/10.1016/S0022-5193(03)00017-1), Journal of Theoretical Biology, 2003

6- [Molecular-dynamics simulations of carbon nanotubes as gigahertz oscillators](https://doi.org/10.1103/PhysRevLett.90.055504), Physical Review Letters, 2003

**2002**

*[Tese de Doutorado](https://doi.org/10.47749/T/UNICAMP.2004.304304), 2002

5- [Identifying relevant molecular descriptors related to carcinogenic activity of Polycyclic Aromatic Hydrocarbons (PAHs) using pattern recognition methods](https://doi.org/10.1021/ci025577+), Journal of Chemical Information and Computer Sciences, 2002

4- [Structure-activity relationship (SAR) studies of the tripos benchmark steroids](https://doi.org/10.1016/S0166-1280(02)00578-X), Journal of Molecular Structure-Theochem, 2002

**2001**

**2000**

*[Dissertação de Mestrado](https://doi.org/10.47749/T/UNICAMP.2000.433887), 2000

3- [Influence of rough substrates on the morphology evolution of epitaxial films](https://doi.org/10.1103/PhysRevB.61.13703), Physical Review B, 2000

**1999**

2- [Growth of Be-doped homoepitaxial GaAs films on rough substrates](https://doi.org/10.1016/S0022-0248(99)00243-2), Journal of Crystal Growth, 1999

**1998**

1- [Surface morphologies in GaAs homoepitaxy: Mound formation and evolution](https://doi.org/10.1103/PhysRevB.58.1947), Physical Review B, 1998
